baseurl = "https://qwyng.dev"
languageCode = "ja"
hasCJKLanguage = true
title = "QWYNG.dev"
theme = "hugo_theme_pickles"

googleAnalytics = "G-9JVVYL7X5D"

[params]
  paginate = 5
  hideWordCount = 1
  hideReadingTime = 1

  # OGP default image (used when page doesn't specify og_image/images)
  # Can be absolute URL (https://...) or a path under /static (e.g. "/android-chrome-384x384.png").
  default_og_image = "/android-chrome-384x384.png"

  # Social accounts. Links to these accounts are displayed in the header and footer.
  twitter = "qwyngg"
  github = "QWYNG"
  # Uncomment and add accounts if needed.
  # facebook = ""
  # instagram = ""
  # googleplus = ""
  # npm = ""
  # codepen = ""
  # dribbble = ""
  # fivehundredpx = ""
  # flickr = ""
  # pinterest = ""
  # tumblr = ""
  # vimeo = ""
  # youtube = ""
  # linkedin = ""

  # Author information
  author = "QWYNG (Hiroaki Osawa)"
  authorwebsite = "https://qwyng.dev"
  avatar = "android-chrome-384x384.png"
  contact = "mailto:hiroaki@qwyng.dev"
  bio = "QWYNG(Hiroaki Osawa)という人間のブログです ワイワイ"
  
  # Short subtitle/tagline
  subtitle = "クワイング"
  
  # Logo and favicon
  logo = "android-chrome-384x384.png"
  favicon = "favicon.ico"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 1

  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    identifier = "rss"
    name = "RSS"
    url = "/index.xml"
    weight = 3